update yaml files

diff --git a/CI/jobs/RHN/entitlement-rhn-defaults.yaml b/CI/jobs/RHN/entitlement-rhn-defaults.yaml
--- a/CI/jobs/RHN/entitlement-rhn-defaults.yaml
+++ b/CI/jobs/RHN/entitlement-rhn-defaults.yaml
@@ -1,5 +1,5 @@
 - defaults:
-    name: entitlement-cdn-base
+    name: entitlement-rhn-base
     description: |
         Purpose: Basic config for entitlement testing.
     concurrent: true
@@ -25,25 +25,15 @@
             # Export testing environment variables
             export Manifest_URL=$Manifest_URL
             export Distro=$Distro
-            export CDN=$CDN
-            export Candlepin=$Candlepin
-            export Blacklist=$Blacklist
-            export Release_Version=$Release_Version
+            export RHN=$RHN
             export Variant=$Variant
             export Arch=$Arch
-
-            env | grep "^PID="
-            if [ $? -eq 0 ]; then
-                export PID=$PID
-            else
-                export PID=$Product_ID
-            fi
 
             # Generate property file to inject environment variables
             echo BUILD_TAG=$BUILD_TAG > build.prop
 
             # Prepare polarion plugin property file
-            master_release=`python -c """import os; distro=os.environ['Distro']; print distro.split('-')[1].split('.')[0]"""`
+            master_release=`python -c """import os; distro = os.environ['Distro']; print distro.split('-')[2].split('.')[0] if 'LE' in distro else distro.split('-')[1].split('.')[0]"""`
             if [ "$master_release" == "6" ]; then
                 cp $WORKSPACE/entitlement-validation/CI/polarion/POLARION_PROPS_RHEL6.txt $WORKSPACE/POLARION_PROPS.txt
             elif [ "$master_release" == "7" ]; then
@@ -60,26 +50,38 @@
             # Run klist before provision to make sure have a valid kerberos ticket
             klist 
 
-            # Modify bkr.json to provision suitable beaker system
+            # Modify bkr.json to provision beaker system
             bkr_path=$WORKSPACE/entitlement-validation/CI/config/bkr.json
             sed -i -e "s/DISTRO/$Distro/g" -e "s/VARIANT/$Variant/g" -e "s/ARCH/$Arch/g" $bkr_path
 
             # Provision testing system in beaker
-            #$WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=qeos --project_defaults=entitlement-validation/CI/config/project-defaults \
+            $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=qeos --project_defaults=entitlement-validation/CI/config/project-defaults \
             --topology=entitlement-validation/CI/config/bkr --ssh_keyfile=entitlement-validation/CI/keys/ent-ci --name=$Distro_$Variant_$Arch
-            #STATUS=$?
+            PROVISION_STATUS=$?
 
-            echo EXISTING_NODES=test09-64.sysmgmt.lab.eng.rdu2.redhat.com > RESOURCES.txt
-            STATUS=1
-            if [ "$STATUS" == 0 ]; then
+            #echo EXISTING_NODES=hp-dl120gen9-01.khw.lab.eng.bos.redhat.com > RESOURCES.txt
+            #PROVISION_STATUS=0
+            if [ $PROVISION_STATUS -eq 0 ]; then
                 echo "Succeed to provison beaker system!"
-                . entitlement-validation/prepare.sh cdn
+                pushd entitlement-validation/
+                . prepare.sh rhn
                 PREPARE_STATUS=$?
+                echo PREPARE_STATUS=$PREPARE_STATUS
+                popd
                 if [ $PREPARE_STATUS -eq 0 ]; then 
                     # Run testing with nosetests
-                    nosetests entitlement-validation/CDN/Tests/*.py --with-xunit --xunit-file=nosetests.xml --logging-level=INFO --logging-format='%(asctime)s %(levelname)5s|%(filename)22s:%(lineno)4d|: %(message)s' --logging-datefmt="%Y-%m-%d" --logging-clear-handlers
-                    #nosetests entitlement-validation/test_cdn.py --with-xunit --xunit-file=nosetests.xml
+                    pushd entitlement-validation/
+                    nosetests RHN/Tests/*.py --with-xunit --nocapture --xunit-file=../nosetests.xml
+                    TEST_STATUS=$?
+                    echo TEST_STATUS=$TEST_STATUS
+                    popd
+                    if [ $TEST_STATUS -ne 0 ]; then 
+                        echo "ERROR: Failed to do testing!"
+                        #extendtesttime.sh 99
+                        exit 1
+                    fi
                 else
+                    echo "ERROR: Failed to prepare testing!"
                     exit 1
                 fi
             else
@@ -91,10 +93,10 @@
             properties-file: build.prop
     publishers:
         - archive:
-            artifacts: '*.txt, *.json, *.xml, *.properties, redhat.repo, **/*.log, manifest/**'
+            artifacts: '*.txt, *.json, *.xml, *.properties, **/redhat.repo, **/**/*.log, **/manifest/*.xml, **/manifest/*.json'
             allow-empty: 'true'
         - ci-polarion:
-            url: 'https://polarion-node01.rhev-ci-vms.eng.rdu2.redhat.com/polarion/ws/services/'
+            url: 'https://polarion.engineering.redhat.com/polarion/ws/services/'
             user: ftan
             password: ''
             xunit-name-regex: 'nosetests.xml'
@@ -130,29 +132,3 @@
         - workspace-cleanup
         - timestamps
 
-- defaults:
-    name: entitlement-cdn-parameters
-    description: |
-        Purpose: Define the parameters used for entitlement testing.
-    concurrent: true
-    parameters:
-        - string:
-            name: manifest_url
-            default: http://hp-z220-11.qe.lab.eng.nay.redhat.com/projects/content-sku/manifests/rhcmsys8/15017-package-manifest.json
-            description:
-        - string:
-            name: Distro
-            default: RHEL-7.2-20150904.0
-            description:
-        - choice:
-            name: CDN
-            choices:
-              - QA
-              - Prod
-            description:
-        - choice:
-            name: Candlepin
-            choices:
-              - Stage
-              - Prod
-            description:
